// SA Council Regions
export const SA_COUNCIL_REGIONS = [
  'Adelaide City Council',
  'Adelaide Hills Council',
  'Alexandrina Council',
  'Barossa Council',
  'Barunga West Council',
  'Berri Barmera Council',
  'Campbelltown City Council',
  'Cedar Valley Council',
  'Charles Sturt City Council',
  'Clare and Gilbert Valleys Council',
  'Cleve District Council',
  'Coober Pedy District Council',
  'Coorong District Council',
  'Copper Coast Council',
  'Elliston District Council',
  'Flinders Ranges Council',
  'Franklin Harbour Council',
  'Gawler Town Council',
  'Goyder Regional Council',
  'Grant District Council',
  'Holdfast Bay City Council',
  'Kangaroo Island Council',
  'Karoonda East Murray Council',
  'Kimba District Council',
  'Kingston District Council',
  'Light Regional Council',
  'Lower Eyre Peninsula Council',
  'Loxton Waikerie Council',
  'Mallala District Council',
  'Marion City Council',
  'Mid Murray Council',
  'Mitcham City Council',
  'Mount Barker District Council',
  'Mount Gambier City Council',
  'Mount Remarkable District Council',
  'Murray Bridge Rural City Council',
  'Naracoorte Lucindale Council',
  'Northern Areas Council',
  'Norwood Payneham and St Peters City Council',
  'Onkaparinga City Council',
  'Orroroo Carrieton District Council',
  'Peterborough District Council',
  'Playford City Council',
  'Port Adelaide Enfield City Council',
  'Port Augusta City Council',
  'Port Lincoln City Council',
  'Port Pirie City and Districts Council',
  'Prospect City Council',
  'Renmark Paringa Council',
  'Robe District Council',
  'Roxby Downs Municipality',
  'Salisbury City Council',
  'Southern Mallee District Council',
  'Streaky Bay District Council',
  'Tatiara District Council',
  'Tea Tree Gully City Council',
  'The Coorong District Council',
  'Tumby Bay District Council',
  'Unley City Council',
  'Victor Harbor City Council',
  'Wakefield Regional Council',
  'Walkerville Town Council',
  'Wattle Range Council',
  'West Torrens City Council',
  'Whyalla City Council',
  'Wudinna District Council',
  'Yankalilla District Council',
  'Yorke Peninsula Council'
];

// Adelaide Hills Townships
export const ADELAIDE_HILLS_TOWNSHIPS = [
  'Aldgate',
  'Balhannah',
  'Bridgewater',
  'Carey Gully',
  'Charleston',
  'Crafers',
  'Echunga',
  'Forreston',
  'Gumeracha',
  'Hahndorf',
  'Heathfield',
  'Lobethal',
  'Lenswood',
  'Macclesfield',
  'Meadows',
  'Mount Barker',
  'Mylor',
  'Nairne',
  'Norton Summit',
  'Oakbank',
  'Piccadilly',
  'Stirling',
  'Strathalbyn',
  'Summertown',
  'Uraidla',
  'Verdun',
  'Woodside',
  'Other'
];

// Generate day options (1-31)
export const DAYS = Array.from({ length: 31 }, (_, i) => i + 1);

// Month options
export const MONTHS = [
  { value: '01', label: 'January' },
  { value: '02', label: 'February' },
  { value: '03', label: 'March' },
  { value: '04', label: 'April' },
  { value: '05', label: 'May' },
  { value: '06', label: 'June' },
  { value: '07', label: 'July' },
  { value: '08', label: 'August' },
  { value: '09', label: 'September' },
  { value: '10', label: 'October' },
  { value: '11', label: 'November' },
  { value: '12', label: 'December' }
];

// Generate year options (1920 to current year)
const currentYear = new Date().getFullYear();
export const YEARS = Array.from({ length: currentYear - 1919 }, (_, i) => currentYear - i);

// Countries list for country of birth field
export const COUNTRIES = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];
